SELECT ROUND(a.LAT_N, 4)
FROM STATION a
WHERE (
    SELECT COUNT(*) 
    FROM STATION b 
    WHERE b.LAT_N <= a.LAT_N
) >= (SELECT COUNT(*) FROM STATION) / 2
AND (
    SELECT COUNT(*) 
    FROM STATION c 
    WHERE c.LAT_N >= a.LAT_N
) >= (SELECT COUNT(*) FROM STATION) / 2